version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    entrypoint: ["sh", "./entrypoint.sh"]
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app

volumes:
  pgdata: 