version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    restart: always
    environment:
      POSTGRES_USER: ackee
      POSTGRES_PASSWORD: ackee
      POSTGRES_DB: ackee_box
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    command: sh -c "npm install && npm run dev"
    environment:
      DATABASE_URL: postgres://ackee:ackee@postgres:5432/ackee_box
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app

volumes:
  pgdata: 